cockroach:
  image: cockroachdb/cockroach-dev
  command: start --stores=hdd=/data --gossip=self://
  expose:
    - "8080"
  volumes:
    - /tmp/test-disk1:/data
cockroachpython:
  build: .
  links:
    - cockroach
